# Script Title: UpSet Plot of Cross-Species Differentially Abundant Orthogroups
# 
# Description: Generates UpSet plots showing shared and unique orthogroup-level 
#              differential abundance (DAP) patterns across species. Merges Tripsacum 
#              2019 and 2022 datasets, separates "Up" and "Down" regulated proteins, 
#              and visualizes species overlap combinations.
#
# Author: Elad Oren
# Created: 2025-01-01
# Last Modified: 2025-04-27
#
# Input: 
#   - 3b_long_log2FC_DAP_rank_protein_id.csv - Long-format dataset with protein IDs and DAP classifications
#
# Output:
#   - (No direct file output, plots are generated interactively; save manually if needed)
#
# Dependencies: dplyr, tidyr, readr, UpSetR, grid
#
# Notes: Species combinations are generated by orthogroup for each DAP status ("Up" and "Down"). 
#        UpSet plots summarize the number of orthogroups shared among different species sets. 
#        "Trip19" and "Trip22" are merged into a single "Trip" group prior to plotting.


rm(list = ls())
library(dplyr)
library(tidyr)
library(UpSetR) # classic UpSet plots (or ComplexUpset if you want prettier ones)
library(grid)





# Load required packages
library(readr)
library(dplyr)

# Read in the CSV file using read_csv from the readr package.
# Then, replace any instance of "Trip19" or "Trip22" in the species column with "Trip".
dat <- read_csv("3b_long_log2FC_DAP_rank_protein_id.csv") %>%
  mutate(species = if_else(species %in% c("Trip19", "Trip22"), "Trip", species)) %>%
  filter(!is.na(orthogroup)) # Remove rows with NA in the orthogroup column

### Processing for DAP = "UP"
# Filter to include only rows with DAP equal to "UP"
dat_up <- dat %>% 
  filter(DAP == "Up")

# Remove duplicate observations for each orthogroup and species 
# (this combines occurrences where the same orthogroup was detected in both trips)
dat_up_unique <- dat_up %>% 
  distinct(orthogroup, species)

# For each orthogroup, generate a sorted combination of species names where it was detected.
# This produces a unique string (e.g., "Ag&Mg&Pv&Trip") representing the PAV.
up_combinations <- dat_up_unique %>%
  group_by(orthogroup) %>%
  summarize(species_comb = paste(sort(unique(species)), collapse = "&"), .groups = "drop")

# Count how many orthogroups are present for each unique species combination.
up_counts <- up_combinations %>%
  group_by(species_comb) %>%
  summarize(count = n(), .groups = "drop") %>%
  arrange(desc(count))

# Create the UpSetR named vector for "UP", where each name is the species combination 
# and the value is the count.
input_up <- setNames(up_counts$count, up_counts$species_comb)
cat("Up vector:\n")
print(input_up)



# Generate UpSet plot
upset(fromExpression(input_up), 
      nintersects = 40, 
      nsets = 6, 
      order.by = "freq", 
      decreasing = TRUE, 
      mb.ratio = c(0.6, 0.4),
      number.angles = 0, 
      text.scale = 2, 
      point.size = 2.8, 
      line.size = 1,
      sets.bar.color = "#648FFF"
)



### Processing for DAP = "DOWN"
# Filter to include only rows with DAP equal to "DOWN"
dat_down <- dat %>% 
  filter(DAP == "Down")

# Remove duplicate observations for each orthogroup and species
dat_down_unique <- dat_down %>% 
  distinct(orthogroup, species)

# For each orthogroup, generate a sorted combination of species names.
down_combinations <- dat_down_unique %>%
  group_by(orthogroup) %>%
  summarize(species_comb = paste(sort(unique(species)), collapse = "&"), .groups = "drop")

# Count the unique combinations.
down_counts <- down_combinations %>%
  group_by(species_comb) %>%
  summarize(count = n(), .groups = "drop") %>%
  arrange(desc(count))

# Create the UpSetR named vector for "DOWN"
input_down <- setNames(down_counts$count, down_counts$species_comb)
cat("Down vector:\n")
print(input_down)


# Generate UpSet plot
upset(fromExpression(input_down), 
      nintersects = 40, 
      nsets = 6, 
      order.by = "freq", 
      decreasing = TRUE, 
      mb.ratio = c(0.6, 0.4),
      number.angles = 0, 
      text.scale = 2, 
      point.size = 2.8, 
      line.size = 1,
      sets.bar.color = "#DC267F"
)
